---
version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    ignore:
      - dependency-name: "io.dropwizard:dropwizard-dependencies"
        # We don't want to upgrade to Dropwizard 5.x just yet
        versions:
          - ">= 5"
      - dependency-name: "io.dropwizard.modules:dropwizard-testing-junit4"
        # We don't want to upgrade to Dropwizard 5.x just yet
        versions:
          - ">= 5"
      - dependency-name: "org.testcontainers:testcontainers-bom"
        # testcontainers v2 needs refactoring on our end
        versions:
          - ">= 2"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - govuk-pay
      - java
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    ignore:
      - dependency-name: "eclipse-temurin"
        versions:
          - "> 21"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - govuk-pay
      - docker
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - govuk-pay
      - github_actions
