name: Post Merge

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

concurrency: publicapi-post-merge

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  publish-publicapi-consumer-contract-tests:
    needs: tests
    runs-on: ubuntu-latest

    name: Publish and tag publicapi consumer pact
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Set up JDK 11
        uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache pacts directory
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0
        with:
          path: target/pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Publish and tag publicapi consumer pact
        run: |
          mvn pact:publish -DPACT_BROKER_URL=https://pact-broker-test.cloudapps.digital \
          -DPACT_BROKER_USERNAME=${{ secrets.pact_broker_username }} \
          -DPACT_BROKER_PASSWORD=${{ secrets.pact_broker_password }} -DPACT_CONSUMER_TAG=master \
          -DPACT_CONSUMER_VERSION=${{ github.sha }}

  ledger-provider-contract-tests:
    needs: publish-publicapi-consumer-contract-tests
    uses: alphagov/pay-ledger/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: publicapi
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  connector-provider-contract-tests:
    needs: publish-publicapi-consumer-contract-tests
    uses: alphagov/pay-connector/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: publicapi
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  tag-release:
    needs:
      - ledger-provider-contract-tests
      - connector-provider-contract-tests
    permissions:
      contents: write
    uses: alphagov/pay-ci/.github/workflows/_create-alpha-release-tag.yml@master
