name: Github Actions Tests

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  integration-tests:
    name: Unit and Integration tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - name: Set up JDK 11
        uses: actions/setup-java@f69f00b5e5324696b07f6b1c92f0470a6df00780
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache pacts directory
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0
        with:
          path: target/pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Pull docker image dependencies
        run: |
          docker pull redis:latest
      - name: Run unit and integration tests
        run: mvn clean verify
